### ISSUE TITLE
see if it *needs* to run as root

### ISSUE THREAD

**Issue by phillmv** [appcanary/agent#96]

**Comment by phillmv** [comment]
Turns out Mike's scripts create an appcanary user!

**Comment by phillmv** [comment]
The customer requesting this specified that they have to be able to install it without root. I don't think that's possible.

>In addition, they don't want to install packages under root that aren't in official Ubuntu repositories.

We'd have to modify all the install scripts to not freak out cos of permissions, add a flag for setting where the log file should be and ship a custom start script.

They might be able to make it work via `dpkg-deb -x`.

**Comment by phillmv** [comment]
Should be good to go via:

dpkg -x package.deb folder-to-extract-to/

and running the /usr/sbin/appcanary binary directly.

**Comment by MacLeodMike** [comment]
I believe both yum and apt (and aptitude, etc) require root in order to access and modify the package database(s). Basically, even if the app doesn't require root I doubt you'll have any luck installing it without root.

But yeah, they should be able to crack open the deb/rpm, extract the application and files to /opt or wherever they want to install the application, create the appcanary user, and have a perfectly fine go of it.

Seems like a lot of extra work for no real discernible gain, but corporate policy will be corporate policy.

**Comment by phillmv** [comment]
@MacLeodMike not corporate policy per se; they host some of their apps on semi managed hosting, so their sysadmin is not a fan of opening up some rando repo :).
